version: '3'

services:
    test-saml-idp:
        image: kristophjunge/test-saml-idp
        ports:
            - '8080:8080'
            - '8443:8443'
        environment:
            SIMPLESAMLPHP_SP_ENTITY_ID: saml-poc
            SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:8000/complete/saml/
        volumes:
            - ./users_saml.php:/var/www/simplesamlphp/config/authsources.php
        container_name: testsamlidp
